- include/envoy/tcp/conn_pool.h
- source/common/http/websocket/ws_handler_impl.cc
- source/common/tcp/conn_pool.cc
- source/common/tcp/conn_pool.h
- source/common/tcp_proxy/BUILD
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/tcp_proxy/tcp_proxy.h
- source/extensions/filters/network/thrift_proxy/router/router_impl.cc
- source/extensions/filters/network/thrift_proxy/router/router_impl.h
- test/common/http/conn_manager_impl_test.cc
- test/common/network/filter_manager_impl_test.cc
- test/common/tcp/conn_pool_test.cc
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/extensions/filters/network/thrift_proxy/router_test.cc
- test/integration/tcp_conn_pool_integration_test.cc
- test/mocks/tcp/mocks.cc
- test/mocks/tcp/mocks.h
This reverts commit 04616d6764c77f1bb48bf1f3496c8378bb11dd2f.
Fixes istio/istio#8310 (once pulled into istio/proxy and istio/istio).
> Revert "tcp_proxy: convert TCP proxy to use TCP connection pool (#4067)"

- examples/wasm/README.md
*Description*:
The existing wasm example does not explain how to recompile an wasm filter. The PR describe the steps.
*Risk Level*: 
*Testing*:
examples/wasm/README.md
> Add wasm build instructions to example/wasm

- source/extensions/common/wasm/wasm.cc
*Description*:
As addressed in #14 , add suffix "PROXY" to _REGISTER on proxy related function registration.
Also rename corresponding _GET and reorder onDone and onLog
*Risk Level*: 
LOW
*Testing*: 
> rename _REGISTER and _GET

- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
- source/extensions/common/wasm/wavm/wavm.cc
> wasm: move implementation details into WasmVm abstraction layer.

- api/wasm/cpp/proxy_wasm_intrinsics.cc
- api/wasm/cpp/proxy_wasm_intrinsics.h
- api/wasm/cpp/proxy_wasm_intrinsics.js
- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
This includes several changes to make timer work for wasm module:
* instead of copying dispatcher from base wasm, copy the dispatcher from filter construction function. dispatcher from base wasm cannot be used in thread local context due to thread safe check in envoy.
* remove `tick_` function pointer, seems to be usefulness. 
* add ontick and set period into wasm intrinsic api.
> Make timer work for wasm module

- api/wasm/cpp/proxy_wasm_intrinsics.h
- api/wasm/cpp/proxy_wasm_intrinsics.js
- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
- source/extensions/common/wasm/wavm/wavm.cc
Add a new API method `getCurrentTimeNanoseconds` utilizing enovy's time source.
> Add clock into intrinsic api into wasm runtime

- source/common/http/codec_client.h
- source/common/http/http1/conn_pool.cc
- source/common/http/http1/conn_pool.h
- test/common/http/http1/conn_pool_test.cc
*Description*:
*Risk Level*:
*Testing*:
> Http10 without keep-alive means close

- source/common/http/http1/conn_pool.cc
- source/common/http/http1/conn_pool.h
*Description*: Delay connection reuse until we have done a poll cycle to detect closed connections.
*Risk Level*: low
*Testing*: hand
*Docs Changes*: N/A
*Release Notes*: N/A
[Optional Fixes #Issue] #13848
> Fix connection reuse by delaying a poll cycle.

- bazel/foreign_cc/luajit.patch
Migration from the build recipes to foreign_cc rules resulted
in dependencies being built with different compiler flags.
Among other things, those compiler flags were added:
-ffunction-sections -fdata-sections
use of which leads to LuaJIT panicking:
PANIC: unprotected error in call to Lua API
and Envoy subsequently crashing.
Broken in #6168.
Fixes istio/istio#13722.
*Description*:
*Risk Level*:
*Testing*:
> cherry-pick into 1.2:  lua: prevent LuaJIT from panicking. (#6994)

- source/common/http/codec_client.h
- source/common/http/http1/conn_pool.cc
- source/common/http/http1/conn_pool.h
- test/common/http/http1/conn_pool_test.cc
*Description*:
*Risk Level*:
*Testing*:
> 1.2 cherry-pick:  Make HTTP/1.0 responses without Connection: keep-alive mean close. (#7124)

- docs/root/configuration/http_filters/lua_filter.rst
- docs/root/intro/version_history.rst
- source/common/crypto/utility.cc
- source/common/crypto/utility.h
- source/extensions/filters/http/lua/BUILD
- source/extensions/filters/http/lua/lua_filter.cc
- source/extensions/filters/http/lua/lua_filter.h
- source/extensions/filters/http/lua/wrappers.cc
- source/extensions/filters/http/lua/wrappers.h
- test/common/crypto/utility_test.cc
- test/extensions/filters/http/lua/lua_filter_test.cc
- test/extensions/filters/http/lua/lua_integration_test.cc
Description: Expose functions for users to verify digital signature in Lua script
Risk Level: Low
Testing: unit test, integration
Docs Changes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-ddc999700fdafb43c2cdcafcc7a4b887
Release Notes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-d8d3e33358b55e6c0466dd1bb5f40c79
Fixes #Issue: #7009
*Description*:
*Risk Level*:
*Testing*:
> cherry-pick into 1.2:  filter: exposed functions to Lua to verify digital signature (#7050)

- api/envoy/admin/v2alpha/clusters.proto
- docs/root/intro/version_history.rst
- source/server/http/admin.cc
- test/server/http/admin_test.cc
> Revert "admin: add host priority and hostname to cluster response"

- source/common/network/socket_option_impl.cc
- source/common/network/socket_option_impl.h
- test/common/network/socket_option_impl_test.cc
> network: fix misaligned memory access in setsockopt().

- source/common/common/utility.cc
- source/common/common/utility.h
- source/common/http/headers.h
- source/common/http/http1/codec_impl.cc
- test/common/common/utility_speed_test.cc
- test/common/common/utility_test.cc
- test/common/http/http1/codec_impl_test.cc
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Do not 503 on Upgrade: h2c instead remove the header and ignore.

- docs/root/intro/version_history.rst
- source/common/common/utility.cc
- source/common/common/utility.h
- source/common/http/headers.h
- source/common/http/http1/codec_impl.cc
- test/common/common/utility_speed_test.cc
- test/common/common/utility_test.cc
- test/common/http/http1/codec_impl_test.cc
Description: When a request comes in on http1 with "upgrade: h2c", the current behavior is to 503.  Instead we should ignore the upgrade and remove the header and continue with the request as http1.
Testing: Unit test. Hand test with ithub.com/rdsubhas/java-istio client server locally.
Release Notes:  http1: ignore and remove Upgrade: h2c.
Fixes istio/istio#16391
Cherry-pick from envoyproxy/envoy
> Do not 503 on Upgrade: h2c instead remove the header and ignore. (#7981)

- source/extensions/filters/network/http_connection_manager/config.cc
- test/extensions/filters/network/http_connection_manager/config_test.cc
https://github.com/istio/istio/issues/16985
Root cause: https://github.com/envoyproxy/envoy/pull/6986/files#diff-c68454405a6c92916edd63682d33246fL234
`random_sampling` is a `Percent`: 
https://github.com/envoyproxy/envoy/blob/38b926c63f347a70c933e0854ee9f31b1d2e85ce/api/envoy/config/filter/network/http_connection_manager/v3alpha/http_connection_manager.proto#L111
which ranges [0.0, 100.0]. The current code caps random sampling rate at 1%. This fix brings back the percentage numerator rounding to 10000.
> fix random sample fraction percent

- WASM.md
- api/wasm/cpp/Dockerfile-sdk
- api/wasm/cpp/Makefile.base
- api/wasm/cpp/Makefile.base_lite
- api/wasm/cpp/README.md
- api/wasm/cpp/build_wasm.sh
- api/wasm/cpp/sdk_container.sh
- api/wasm/rust/README.md
* Add Dockerfile for the C++ SDK.
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Wasm dockerfile (#174)

- bazel/repository_locations.bzl
Signed-off-by: Daniel Grimm <dgrimm@redhat.com>
Description: update jwt_verify_lib to support RS384 and RS512 tokens
Risk Level: low
Testing: upstream unit tests
Docs Changes: none
Release Notes: none
Fixes https://github.com/istio/istio/issues/15380
This had previously been merged into the 1.2 release track but is now missing from the 1.3 track due to the switchover to envoy filters. This only targets `release-1.3` because it has been merged upstream (https://github.com/envoyproxy/envoy/pull/8212) and I expect it to be automatically pulled into `master`.
> Update dependency: jwt_verify_lib

- include/envoy/thread_local/thread_local.h
- source/common/common/non_copyable.h
- source/common/config/config_provider_impl.cc
- source/common/config/config_provider_impl.h
- source/common/router/rds_impl.cc
- source/common/thread_local/thread_local_impl.cc
- source/common/thread_local/thread_local_impl.h
- test/common/thread_local/thread_local_impl_test.cc
- test/mocks/thread_local/mocks.h
Description: Import thread local changes from envoyproxy/master and apply to RDS in the same manner as was applied in envoyproxy/master in order to address a segfault.
Risk Level:
Testing: unit tests (e2e in future)
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/istio/istio/issues/17699
> Apply fix for use-after-free in Envoy ThreadLocal Slot.

- docs/root/intro/arch_overview/security/rbac_filter.rst
- include/envoy/stream_info/stream_info.h
- source/common/stream_info/stream_info_impl.h
- source/extensions/filters/common/expr/BUILD
- source/extensions/filters/common/expr/context.cc
- source/extensions/filters/common/expr/context.h
- test/common/stream_info/stream_info_impl_test.cc
- test/common/stream_info/test_util.h
- test/extensions/filters/common/expr/context_test.cc
- test/mocks/stream_info/mocks.h
Description: Add response flags into expression context
Risk Level: low
Testing: unit test
Docs Changes:
Release Notes:
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Add response flags into cel expression context (#8827)

- bazel/repository_locations.bzl
Cherry pick of https://github.com/envoyproxy/envoy/pull/8908/commits/b9f8f79823088277e69a8a84956cc37108ab93fb
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release-1.4] update opencensus sha (#8908)

- api/envoy/config/accesslog/v2/als.proto
- api/envoy/config/accesslog/v3alpha/als.proto
- api/envoy/data/accesslog/v2/accesslog.proto
- api/envoy/data/accesslog/v3alpha/accesslog.proto
- docs/root/configuration/observability/access_log.rst
- docs/root/intro/arch_overview/advanced/data_sharing_between_filters.rst
- include/envoy/stream_info/BUILD
- include/envoy/stream_info/filter_state.h
- source/common/access_log/access_log_formatter.cc
- source/common/access_log/access_log_formatter.h
- source/common/router/string_accessor_impl.h
- source/extensions/access_loggers/grpc/BUILD
- source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
- source/extensions/access_loggers/grpc/grpc_access_log_utils.h
- source/extensions/access_loggers/grpc/http_grpc_access_log_impl.cc
- source/extensions/access_loggers/grpc/http_grpc_access_log_impl.h
- source/extensions/access_loggers/grpc/tcp_grpc_access_log_impl.cc
- source/extensions/common/wasm/BUILD
- source/extensions/common/wasm/wasm_state.cc
- source/extensions/common/wasm/wasm_state.h
- test/common/access_log/BUILD
- test/common/access_log/access_log_formatter_test.cc
- test/extensions/access_loggers/grpc/BUILD
- test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
Cherry-pick envoyproxy/envoy-wasm#297
Signed-off-by: Lizan Zhou <lizan@tetrate.io>
> Make wasm state serializable.

- bazel/repositories.bzl
- bazel/repository_locations.bzl
Description:
Change (non-existent) https://github.com/eile/tclap/ to https://github.com/mirror/tclap/. I didn't validate the new mirror in any way, but the downloded release file sha256sum stays the same. In the future the releases should probably be downloaded from the real upstream. However the release 1.2.1 tarball from https://sourceforge.net/projects/tclap/files/ did not have the same sha256sum as the release file which Envoy uses.
Testing: N/A
Release Notes:
Fixes #9071 
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
> [release-1.4] bazel: replace tclap mirror. (#9072)

- bazel/repositories.bzl
- bazel/repository_locations.bzl
Description:
Change (non-existent) https://github.com/eile/tclap/ to https://github.com/mirror/tclap/. I didn't validate the new mirror in any way, but the downloded release file sha256sum stays the same. In the future the releases should probably be downloaded from the real upstream. However the release 1.2.1 tarball from https://sourceforge.net/projects/tclap/files/ did not have the same sha256sum as the release file which Envoy uses.
Testing: N/A
Release Notes:
Fixes #9071
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
> [release-1.1] bazel: replace tclap mirror. (#9072)

- bazel/repositories.bzl
- bazel/repository_locations.bzl
Description:
Change (non-existent) https://github.com/eile/tclap/ to https://github.com/mirror/tclap/. I didn't validate the new mirror in any way, but the downloded release file sha256sum stays the same. In the future the releases should probably be downloaded from the real upstream. However the release 1.2.1 tarball from https://sourceforge.net/projects/tclap/files/ did not have the same sha256sum as the release file which Envoy uses.
Testing: N/A
Release Notes:
Fixes #9071 
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
> [release-1.3] bazel: replace tclap mirror. (#9072)

- bazel/repositories.bzl
- bazel/repository_locations.bzl
Description:
Change (non-existent) https://github.com/eile/tclap/ to https://github.com/mirror/tclap/. I didn't validate the new mirror in any way, but the downloded release file sha256sum stays the same. In the future the releases should probably be downloaded from the real upstream. However the release 1.2.1 tarball from https://sourceforge.net/projects/tclap/files/ did not have the same sha256sum as the release file which Envoy uses.
Testing: N/A
Release Notes:
Fixes #9071 
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
> [release-1.2] bazel: replace tclap mirror. (#9072)

- docs/root/intro/arch_overview/security/rbac_filter.rst
- source/extensions/filters/common/expr/context.cc
- source/extensions/filters/common/expr/context.h
- test/extensions/filters/common/expr/context_test.cc
This is not a clean cherry-pick due to changes in headers.
@mandarjog @PiotrSikora
> Cherry-pick of https://github.com/envoyproxy/envoy/pull/9839

- source/extensions/filters/common/expr/context.cc
- test/extensions/filters/common/expr/context_test.cc
Signed-off-by: Kuat Yessenov <kuat@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Cherry-pick of https://github.com/envoyproxy/envoy/pull/9862

- docs/root/intro/arch_overview/security/rbac_filter.rst
- source/extensions/filters/common/expr/BUILD
- source/extensions/filters/common/expr/context.cc
- test/extensions/filters/common/expr/context_test.cc
Cherry-picks of #9839 and #9862
> Response total size

- source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Use sts for call credential when STS_PORT is provided in node metadata

- api/envoy/type/matcher/string.proto
- api/envoy/type/matcher/v3/string.proto
- generated_api_shadow/envoy/type/matcher/string.proto
- generated_api_shadow/envoy/type/matcher/v3/string.proto
- source/common/common/matchers.cc
- test/common/common/BUILD
- test/common/common/matchers_test.cc
Cherry-pick https://github.com/envoyproxy/envoy/pull/9868
Ran tests locally and `//test/common/common:matchers_test PASSED in 1.7s`. 
The WASM is failing but should be unrelated to this PR:
```
test/extensions/filters/http/wasm/wasm_filter_test.cc:468:58: error: no member named 'getDataReadOnly' in 'std::__1::shared_ptr<Envoy::StreamInfo::FilterState>'; did you mean to use '->' instead of '.'?
const auto& result = request_stream_info_.filterState().getDataReadOnly<Common::Wasm::WasmState>(
^
->
test/extensions/filters/http/wasm/wasm_filter_test.cc:468:98: error: expected '(' for function-style cast or type construction
const auto& result = request_stream_info_.filterState().getDataReadOnly<Common::Wasm::WasmState>(
~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```
Signed-off-by: Yangmin …
> [release-1.5] add ignore_case to StringMatcher that allows case insensitive exact/prefix/suffix string matching

- source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Corresponding release-1.5 cherry-pick https://github.com/istio/envoy/pull/144
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release-1.4] Use sts for call credential when STS_PORT is provided in node metadata #144

- api/wasm/cpp/proxy_wasm_intrinsics.pb.cc
- api/wasm/cpp/proxy_wasm_intrinsics.pb.h
- api/wasm/cpp/proxy_wasm_intrinsics.proto
- api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.cc
- api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.h
- api/wasm/cpp/proxy_wasm_intrinsics_lite.proto
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Update GrpcService to add StsService. (#411)

- source/common/network/connection_impl.cc
- source/common/network/connection_impl.h
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/tcp_proxy/tcp_proxy.h
- source/extensions/filters/network/tcp_proxy/config.cc
- test/common/http/conn_manager_impl_test.cc
- test/common/network/filter_manager_impl_test.cc
- test/common/stream_info/BUILD
- test/common/stream_info/test_util.h
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/common/upstream/health_checker_impl_test.cc
- test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
- test/extensions/filters/http/lua/lua_filter_test.cc
- test/extensions/filters/http/lua/wrappers_test.cc
- test/extensions/filters/network/tcp_proxy/config_test.cc
- test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc
- test/mocks/stream_info/BUILD
- test/mocks/stream_info/mocks.cc
- test/mocks/stream_info/mocks.h
Signed-off-by: gargnupur <gargnupur@google.com>
Ref: https://github.com/istio/istio/issues/20802
Description: git cherry-pick fade668c7edfbade082b40df1c6b9924bc7a7e0e
Upstream envoy PR: https://github.com/envoyproxy/envoy/pull/9949
Risk Level:
Testing:
Docs Changes:
Release Notes:
12 lines of non-test code changes.
Rest is test.
> Add upstream and downstream info in parent read callbacks in tcp too(#9949)

- api/wasm/cpp/proxy_wasm_api.h
- source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Add x-goog-user-proj header for sts credential

- bazel/repository_locations.bzl
- source/extensions/access_loggers/wasm/config.cc
- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
- source/extensions/filters/http/wasm/wasm_filter.cc
- source/extensions/filters/network/wasm/wasm_filter.cc
- source/extensions/wasm/config.cc
- test/extensions/access_loggers/wasm/config_test.cc
- test/extensions/common/wasm/wasm_test.cc
- test/extensions/filters/http/wasm/wasm_filter_test.cc
- test/extensions/wasm/config_test.cc
- test/extensions/wasm/wasm_speed_test.cc
- test/extensions/wasm/wasm_test.cc
Backport envoyproxy/envoy-wasm#387 and related fixes (envoyproxy/envoy-wasm#400
and envoyproxy/envoy-wasm#413).
> Cache and share the base Wasm VM.

- bazel/envoy_test.bzl
- test/integration/BUILD
Backport envoyproxy/envoy-wasm#422 and its prerequisite (envoyproxy/envoy#10009).
> ci: mark //test/integration:protocol_integration_test as flaky.

- source/extensions/common/wasm/context.cc
- source/extensions/common/wasm/context.h
- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
Backport envoyproxy/envoy-wasm#405 and its cleanup (envoyproxy/envoy-wasm#410).
> Fix Wasm VM shutdown.

- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
> wasm: remove unused "free" function. (#404)

- include/envoy/server/wasm.h
- include/envoy/server/wasm_config.h
- source/extensions/wasm/config.cc
- source/extensions/wasm/config.h
- source/server/server.cc
- source/server/server.h
- test/extensions/wasm/config_test.cc
This change restores Wasm Service, which was accidentally removed
in a bad merge (#321).
It also fixes a number of issuses:
1. Wasm Services were started before Cluster Manager was initialized,
which crashed Envoy when Wasm Service tried to dispatch a callout.
2. Wasm Services (per-thread) were not stored and they were getting
out of scope, so they were immediately destroyed.
3. Wasm Services (singleton) were started twice.
> wasm: restore and fix the Wasm Service. (#440)

- docs/root/intro/version_history.rst
- source/extensions/filters/listener/tls_inspector/tls_inspector.cc
- source/extensions/filters/listener/tls_inspector/tls_inspector.h
- test/extensions/filters/listener/tls_inspector/tls_inspector_benchmark.cc
- test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
- test/extensions/filters/listener/tls_inspector/tls_utility.cc
- test/extensions/filters/listener/tls_inspector/tls_utility.h
Previously, TLS inspector didn't support TLSv1.3 and clients configured
to use only TLSv1.3 were not recognized as TLS clients.
Because TLS extensions (SNI, ALPN) were not inspected, those connections
might have been matched to a wrong filter chain, possibly bypassing some
security restrictions in the process.
> tls_inspector: enable TLSv1.3. (#118)

- source/common/secret/sds_api.h
- source/extensions/transport_sockets/tls/context_config_impl.cc
- test/integration/sds_dynamic_integration_test.cc
Previously, the update callback was called only when the secret
was received for the first time or when its value changed.
This meant that if the same secret (e.g. trusted CA) was used in
multiple resources, then resources using it but configured after
the secret was already received, remained unconfigured until the
secret's value changed.
The missing callback should have resulted in transport factories
stuck in the "not ready" state, however, because of an incorrect
code, the available secret was processed like inlined validation
context, and only rules from the "secret" part of the validation
context were applied, leading to a complete bypass of rules from
the "default" part.
Co-authored-by: Oliver Liu <yonggangl@google.com>
> sds: fix combined validation context validation bypassing (#114)

- include/envoy/buffer/buffer.h
- source/common/buffer/buffer_impl.cc
- source/common/buffer/buffer_impl.h
- test/common/buffer/owned_impl_test.cc
Description: Remove empty slices off the end of buffers after calls to OwnedImpl::commit. The slices reserved when OwnedImpl::reserve is called will sit unused in cases where the 0 bytes are commited, for example, when socket read returns 0 bytes EAGAIN. Trapped slices act like a memory leak until there is a successful read or the socket is closed.
Risk Level: low
Testing: unit
Docs Changes: n/a
Release Notes: n/a
Signed-off-by: Asra Ali <asraa@google.com>
> buffer: release empty slices after commit (#116)

- source/common/buffer/buffer_impl.cc
- test/common/buffer/owned_impl_test.cc
Given that we allow creating zero byte fragments, it'd be good to proactively drain them. For example if someone is doing timing instrumentation and wants to know when Network::Connection data is written to the kernel, it could be useful to have a zero byte sentinel.
Risk Level: Low (I don't think anyone is adding zero byte fragments yet)
Testing: new unit test
Docs Changes: n/a
Release Notes: n/a
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
> buffer: draining any zero byte fragments (#9837) (#109)

- source/common/network/connection_impl.cc
- test/common/network/connection_impl_test.cc
- test/extensions/transport_sockets/tls/ssl_socket_test.cc
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
> network: draining the buffer on close (#9870) (#110)

- docs/root/configuration/http/http_conn_man/stats.rst
- docs/root/intro/version_history.rst
- source/common/http/http1/codec_impl.cc
- source/common/http/http1/codec_impl.h
- source/common/runtime/runtime_features.cc
- source/common/runtime/runtime_impl.cc
- test/common/http/http1/codec_impl_test.cc
- test/integration/integration_admin_test.cc
- test/integration/integration_test.cc
This is similar to the http2 frame protection, but rather than try to
guard
[header block || last body bytes || last chunk in chunk encoding ||
trailer block]
depending on end stream, which just gets messy, I opted to just add an
empty reference counted fragment after the body was serialized, which
appears to work just as well with a small theoretical overhead.  If
folks think the complexity is warranted I can of course do that instead.
Testing: new unit tests, integration test
Docs Changes: stats documented
Release Notes: added
Signed-off-by: Alyssa Wilk <alyssar@chromium.org>
> http: adding response flood protection (#113)

- include/envoy/stream_info/stream_info.h
- source/common/http/conn_manager_impl.cc
- source/common/stream_info/stream_info_impl.h
- source/common/tcp_proxy/tcp_proxy.cc
- test/common/stream_info/stream_info_impl_test.cc
- test/common/stream_info/test_util.h
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/mocks/stream_info/mocks.h
Add ClusterName as a property in StreamInfo. This is because for TCP, there is no RouteEntry and thus we are not able to get clustername for TCP in scenarios where upstream cluster is not healthy
Risk Level: Low
Testing: Unit Tests
Docs Changes:
Release Notes:
Signed-off-by: gargnupur <gargnupur@google.com>
Co-authored-by: Matt Klein <mattklein123@gmail.com>
Description: git cherry-pick 9186ebf374b1bd7d7c65ed1cec748377f88ec0a7 (from envoyproxy/envoy)
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [Release-1.5] Add ClusterInfo as a property in StreamInfo (#10432)

- source/extensions/common/wasm/context.cc
Signed-off-by: gargnupur <gargnupur@google.com>
Remove files
Signed-off-by: gargnupur <gargnupur@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [Release-1.5] Use ClusterInfo from streaminfo to get clustername too

- source/extensions/tracers/zipkin/span_buffer.cc
- source/extensions/tracers/zipkin/span_buffer.h
- source/extensions/tracers/zipkin/util.cc
- source/extensions/tracers/zipkin/util.h
- source/extensions/tracers/zipkin/zipkin_core_types.cc
- source/extensions/tracers/zipkin/zipkin_core_types.h
- test/extensions/tracers/zipkin/BUILD
- test/extensions/tracers/zipkin/span_buffer_test.cc
- test/extensions/tracers/zipkin/zipkin_core_types_test.cc
Cherry pick of https://github.com/envoyproxy/envoy/pull/10400
ref: https://github.com/istio/istio/issues/22968
This patch fixes the wrongly rendered timestamp value of serialized
zipkin span by introducing replacers. This path is chosen since the way
protobuf struct holds numeric data is by using double as its data type and
when it is serialized (through `MessageToJsonString`; internally by
`snprintf`-ing the value to a string) sometimes lead to a value with
scientific notation involved (e.g. 1584324295476870 will be printed as
1.58432429547687e+15). A better solution probably by going down to fix
protobuf `MessageToJsonString`.
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>
in …
> zipkin: Fix wrongly rendered timestamp value (#10400)

- source/extensions/tracers/zipkin/span_buffer.cc
- source/extensions/tracers/zipkin/span_buffer.h
- source/extensions/tracers/zipkin/util.cc
- source/extensions/tracers/zipkin/util.h
- source/extensions/tracers/zipkin/zipkin_core_types.cc
- source/extensions/tracers/zipkin/zipkin_core_types.h
- test/extensions/tracers/zipkin/BUILD
- test/extensions/tracers/zipkin/span_buffer_test.cc
- test/extensions/tracers/zipkin/zipkin_core_types_test.cc
Manual cherry-pick https://github.com/envoyproxy/envoy/commit/01fe4b620f643bea06bdf5cea3443f9b0767fc40
ref issue: https://github.com/istio/istio/issues/22968
This patch fixes the wrongly rendered timestamp value of serialized
zipkin span by introducing replacers. This path is chosen since the way
protobuf struct holds numeric data is by using double as its data type and
when it is serialized (through `MessageToJsonString`; internally by
`snprintf`-ing the value to a string) sometimes lead to a value with
scientific notation involved (e.g. 1584324295476870 will be printed as
1.58432429547687e+15). A better solution probably by going down to fix
protobuf `MessageToJsonString`.
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>
For an explanation of how to fill out the fields, please see the …
> [release-1.6] zipkin: Fix wrongly rendered timestamp value (#10400)

- source/common/upstream/strict_dns_cluster.cc
- test/common/upstream/upstream_impl_test.cc
Description: See https://github.com/envoyproxy/envoy/pull/10728
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
Fixes: https://github.com/istio/istio/issues/22837 and probably other cases about lds not ready, istio proxy not ready.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release-1.4] empty strict dns cluster fix cherry-pick envoyproxy #10728

- source/common/upstream/strict_dns_cluster.cc
- test/common/upstream/upstream_impl_test.cc
Description: See envoyproxy#10728
Signed-off-by: Yuchen Dai silentdai@gmail.com
Fixes: https://github.com/istio/istio/issues/22837 and probably other cases about lds not ready, istio proxy not ready.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release-1.5] empty strict dns cluster fix cherry-pick envoyproxy #10728 
