istio/envoy

source/extensions/common/wasm/wavm/wavm.cc

wasm: call __post_instantiate in start().

---

source/extensions/common/wasm/wasm.h
source/extensions/common/wasm/wavm/wavm.cc

wasm: remove unused parameter from getUserSection().

---

source/extensions/common/wasm/wasm.cc
source/extensions/common/wasm/wasm.h
source/extensions/common/wasm/wavm/wavm.cc

While there, fix a few invalid signatures.

wasm: add a bunch of Emscripten stubs.

---

test/mocks/grpc/mocks.h

Patch gRPC tests.

---

ci/build_container/build_recipes/wavm.sh
ci/prebuilt/BUILD
source/extensions/common/wasm/wavm/wavm.cc

build: update WAVM to latest.

---

ci/build_container/build_container_ubuntu.sh

build: update ninja to version 1.8.2.

---

source/common/http/http1/conn_pool.cc
test/common/http/http1/conn_pool_test.cc

*Description*:
*Risk Level*:
*Testing*:

Fix http1 connection pool test.

---

docs/root/configuration/http_filters/lua_filter.rst
docs/root/intro/version_history.rst
source/extensions/filters/common/lua/BUILD
source/extensions/filters/http/lua/lua_filter.cc
source/extensions/filters/http/lua/lua_filter.h
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/lua_integration_test.cc

Description: Expose functions for users to verify digital signature in Lua script
Risk Level: Low
Testing: unit test, integration
Docs Changes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-ddc999700fdafb43c2cdcafcc7a4b887
Release Notes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-d8d3e33358b55e6c0466dd1bb5f40c79
Fixes #Issue: #7009

filter: exposed functions to Lua to verify digital signature

---

docs/root/configuration/http_filters/lua_filter.rst
docs/root/intro/version_history.rst
source/common/crypto/utility.cc
source/common/crypto/utility.h
source/extensions/filters/http/lua/BUILD
source/extensions/filters/http/lua/lua_filter.cc
source/extensions/filters/http/lua/lua_filter.h
source/extensions/filters/http/lua/wrappers.cc
source/extensions/filters/http/lua/wrappers.h
test/common/crypto/utility_test.cc
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/lua_integration_test.cc

Description: Expose functions for users to verify digital signature in Lua script
Risk Level: Low
Testing: unit test, integration
Docs Changes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-ddc999700fdafb43c2cdcafcc7a4b887
Release Notes: https://github.com/envoyproxy/envoy/compare/master...crazyxy:feature/boringssllua?expand=1#diff-d8d3e33358b55e6c0466dd1bb5f40c79
Fixes #Issue: #7009

filter: exposed functions to Lua to verify digital signature (#7050)

---

api/envoy/admin/v2alpha/clusters.proto
docs/root/intro/version_history.rst
source/server/http/admin.cc
test/server/http/admin_test.cc

*Description*:
*Risk Level*:
*Testing*:

 admin: add host priority and hostname to cluster response

---

api/envoy/admin/v2alpha/clusters.proto
docs/root/intro/version_history.rst
source/server/http/admin.cc
test/server/http/admin_test.cc

*Description*:
*Risk Level*:
*Testing*:

admin: add host priority and hostname to cluster response

---

api/envoy/admin/v2alpha/clusters.proto
docs/root/intro/version_history.rst
source/server/http/admin.cc
test/server/http/admin_test.cc

Revert " admin: add host priority and hostname to cluster response"

---

source/extensions/common/wasm/wasm.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

fix upstream host NULL pointer

---

source/common/protobuf/utility.cc
source/common/protobuf/utility.h
test/common/protobuf/utility_test.cc
test/common/secret/BUILD
test/common/secret/secret_manager_impl_test.cc
tools/spelling_dictionary.txt

Addresses: https://github.com/istio/istio/issues/17383 https://github.com/istio/istio/issues/17139

Cherrypick 647aea1 from envoyproxy/envoy

---

bazel/repository_locations.bzl

[release-1.4] build: update wee8 to 7.9.317.14. (#287)

---

source/extensions/common/wasm/v8/v8.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix TSAN race.

---

source/extensions/common/wasm/exports.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Return the foreign function result.

---

source/extensions/tracers/opencensus/config.cc
source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
source/extensions/tracers/opencensus/opencensus_tracer_impl.h
test/extensions/filters/common/expr/context_test.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix tracer ssl credential

---

api/wasm/cpp/proxy_wasm_intrinsics.pb.cc
api/wasm/cpp/proxy_wasm_intrinsics.pb.h
api/wasm/cpp/proxy_wasm_intrinsics.proto
api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.cc
api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.h
api/wasm/cpp/proxy_wasm_intrinsics_lite.proto

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Update GrpcService to add StsService. (#411)

---

test/extensions/tracers/opencensus/tracer_test.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix opencensus tracer test

---

source/extensions/tracers/opencensus/config.cc
source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
source/extensions/tracers/opencensus/opencensus_tracer_impl.h
test/extensions/tracers/opencensus/tracer_test.cc

Cherry pick #151 #152 and #155 
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

[release-1.5] Fix opencensus tracer for sts

---

ci/do_ci.sh

We don't care about it, and it's currently broken.

ci: stop testing integration with other workspaces. (#382)

---

source/extensions/common/wasm/wasm.cc
source/extensions/common/wasm/wasm.h
source/extensions/filters/http/wasm/wasm_filter.cc
source/extensions/filters/network/wasm/wasm_filter.cc
source/extensions/wasm/config.cc
test/extensions/common/wasm/BUILD
test/extensions/common/wasm/wasm_test.cc

Fix use-after-free error for remote .wasm file accesses. (#427)

---

test/common/stats/BUILD

ci: increase timeout for a few //test/common/stats:... tests.

---

source/extensions/common/wasm/context.cc
source/extensions/common/wasm/context.h

This is kinda dup of https://github.com/istio/envoy/pull/186
Description: Fix memory leak in TCP
Ref: istio/istio#22007
Verified envoy builds locally
Risk Level:
Testing:
Docs Changes:
Release Notes:

[Release-1.5] Fix memory leak in TCP
